// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeroManagementWebApi.Model
{
    public partial class Ability
    {
        public Ability()
        {
            Heroes = new HashSet<Hero>();
        }

        public int AbilityId { get; set; }
        public string AbilityDesc { get; set; }

        public virtual ICollection<Hero> Heroes { get; set; }
    }
}