// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeroManagementWebApi.Model
{
    public partial class Hero
    {
        public string Id { get; set; }
        public string HeroName { get; set; }
        public int AbilityId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int Power { get; set; }
        public string TrainerId { get; set; }

        public virtual Ability Ability { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}