// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeroManagementWebApi.Model
{
    public partial class Trainer
    {
        public Trainer()
        {
            Heroes = new HashSet<Hero>();
        }

        public string Id { get; set; }
        public string TrainerName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Hero> Heroes { get; set; }
    }
}